### ISSUE TITLE
Bug in response.length as undefined

### ISSUE THREAD

**Issue by tacnoman** [pikada-lab/icq-bot-nodejs#2]
Hello (sorry, I cannot speak russian).

I'm trying to create a bot with this lib and I'm receiving this message:

```
(node:29576) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /var/www/icqbot/node_modules/icq-bot/dist/class/Bot.js:60:68
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:29576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

The problem is in this line

```
 53     Bot.prototype.polling = function () {
 54         var _this = this;
 55         if (this.running) {
 56             // Exceptions should not stop polling thread.
 57             // noinspection PyBroadException
 58             try {
 59                 this.eventsGet(this.pollTimeS, this.lastEventId).then(function (response) {
// response.events is undefined :/
 60                     for (var _i = 0, _a = response.events; _i < _a.length; _i++) {
 61                         var event_1 = _a[_i];
 62                         _this.dispatcher.dispatch(new ICQEvent_1.ICQEvent(event_1));
 63                     }
 64                     _this.polling();
 65                 });
 66             }
 67             catch (ex) {
 68                 console.error("Exception while polling!", ex);
 69             }
 70         }
 71     };
```

This is a bug or I made something wrong in my code? I coppied from readme file.

```js
const ICQ = require('icq-bot').default;
const token = '001.0000000000.0000000000:0000';
const bot = new ICQ.Bot(token, {
  name: 'MonitoringPhotoBot',

});

const handlerNewMessage = new ICQ.Handler.Message(ICQ.Filter.url, (bot, event) => {
    const chatId = event.fromChatId;
    console.log(`New Message event.fromChatID = ${chatId}`);
    bot.sendText(chatId, "Message!");
});

const handlerDeleteMessage = new ICQ.Handler.DeletedMessage(null, (bot, event) => {
    const chatId = event.fromChatId;
    console.log(`Deleted Message event.fromChatID = ${chatId}`);
    bot.sendText(chatId, "Зачем!");
});

bot.getDispatcher().addHandler(handlerNewMessage);
bot.getDispatcher().addHandler(handlerDeleteMessage);

bot.startPolling();

```

Thanks for this

**Comment by tacnoman** [comment]
Sorry for this issue
My token was wrong number of chars.

**Comment by pikada-lab** [comment]
Thanks for the feedback.
